### PR TITLE
Solution to scrollbars not showing without a shim

### PR DESCRIPTION
**Pull request by nepo-dev**
Added a solution for the problem with overflow where scrollbars were not showing and added an explanation about this workaround as a commentary in .#nerdbox .nb-content.

### CODE REVIEW

**Comment by nepo-dev** [comment]
Of course, done. Tell me what you think of it when you try it.

**Comment by mikepack** [comment]
This is brilliant. Works all the way back to IE9. Merging. Thank you so much for taking the time to figure this out!

**Comment by mikepack** [comment]
Not sure how to issue the bounty yet, figuring that out.

**Comment by mikepack** [comment]
Apparently you need to submit a claim for the bounty on bountysource. Go ahead and do that and we'll get you some $$$!

**Comment by mikepack** [comment]
@mkitt thought you might be interested in this solution.

**Comment by nepo-dev** [comment]
I'm glad I was of any help! And thanks, I have just claimed it.

**Pull request merged**
