### PR TITLE
Use the `container` option from the current Nerdbox instance

### PR DESCRIPTION
**Pull request by jtrim**
Options are applied to the instance in `Nerdbox.init`, so doing this allows us
to override `container` in the constructor.

### CODE REVIEW

**Comment by mikepack** [comment]
I think you're right, it's likely an oversight that `Nerdbox.options` is in there.

There's [another test](https://github.com/jtrim/nerdbox/blob/constructor-container-override/spec/nerdbox/nerdbox_spec.js#L78-L86) for overriding options. Could you merge your new test into that test?

**Comment by jtrim** [comment]
Yep, although both would be necessary to cover the bug. The problem isn't that `instance.options.container` wasn't being set, it just wasn't being used.

I'll try and get this in today. Thanks!

**Comment by mikepack** [comment]
Ping ping. Any way I can help with this?

**Comment by jtrim** [comment]
I'm still trying to work this in, just haven't had a chance to get around to it. I probably won't actually have time to pay attention to this until later this week.

**Comment by mikepack** [comment]
No problem dude! Thanks for mulling this over.

**Comment by mikepack** [comment]
Merging and making change locally. Thanks Jesse!

**Pull request closed without merging**
