### PR TITLE
Potential fix to scrolling. #15

### PR DESCRIPTION
**Pull request by MichaelArestad**
The down side is the close button is a bit hacky and needs to be the first element in the container.

### CODE REVIEW

**Comment by mikepack** [comment]
Hm, the `text-align: right` makes all of the content right justified as well. I can see this is used to position the close element. This is probably what you mean by hacky?

screen shot 2014-09-02 at 7 35 18 pm

**Comment by jejacks0n** [comment]
If there's a `text-align: left` on `#nerdbox .nb-content` does it continue behaving the same way?

**Comment by MichaelArestad** [comment]
Yep. fixed. I just forgot to include it in original commit.

**Comment by MichaelArestad** [comment]
> Hm, the text-align: right makes all of the content right justified as well. I can see this is used to position the close element. This is probably what you mean by hacky?

Kind of. The hacky bit is really the fixed positioning on the close button using the right align and no set position.

**Comment by jejacks0n** [comment]
I assume that can be positioned in some other way, potentially moving it up one node.

**Comment by mikepack** [comment]
Nice, looks like the `text-align: left` on .nb-content fixed that concern. Noticing this too: on overflowed content, the horizontal scrollbar is positioned on the absolute bottom, not within the lightbox window.

When not scrolled to the bottom, no scrollbar:

no-scroll

When scrolled to the bottom, scrollbar present:

scroll

**Comment by ajaswa** [comment]
@MichaelArestad hit me up if you want to bounce some ideas around.

**Comment by MichaelArestad** [comment]
Fixed. There was an unnecessary  `overflow:auto` on the content container so the scrollbar was there, but below the visible content area.

**Comment by ajaswa** [comment]
@MichaelArestad one minor thing: scroll bar is now showing when there isn't content to scroll.

screen shot 2014-09-02 at 9 35 31 pm

**Comment by jejacks0n** [comment]
check the latest.. I'm on that branch and it seems to work for me in chrome, ff, and safari. Didn't feel like firing up different VMs for various IE versions.

**Comment by jejacks0n** [comment]
The only thing I will comment on is the ajax modal.. the close button isn't working, but that seems broken in master.

**Comment by ajaswa** [comment]
Just pulled it down and tested. 
Latest Chrome on the latest OSX with the latest code. I see horizontal scroll bar when there shouldn't be. 
screen shot 2014-09-02 at 9 42 07 pm

**Comment by jejacks0n** [comment]
screen shot 2014-09-02 at 9 44 30 pm

Version 37.0.2062.94
Google Chrome is up to date.

**Comment by jejacks0n** [comment]
@ajaswa you know I was messing, right? I think of you as being the uber professional.

**Comment by ajaswa** [comment]
@jejacks0n I can never tell ;) 

I think this is the closest we've gotten so far. After messing with my browser window size the horizontal  scroll bar seems to come and go.

**Comment by MichaelArestad** [comment]
Yeah. I suspect it's a browser bug, but I can't replicate it. Then again, I haven't restarted it in a bit. 
image

**Comment by MichaelArestad** [comment]
Works correctly in Canary as well.

**Comment by ajaswa** [comment]
@MichaelArestad yea it seem intermittent. I got it to go away and then it came back. I'll see what I can figure out tomorrow if you guys don't sort it out after I've gone to bed.

**Comment by jejacks0n** [comment]
I can in fact get the horizontal scroll bar in chrome, if I resize the browser slowly it flickers here and there, and can be resized perfectly to let it show but yeah, seems like a browser bug. Doesn't happen in ff or safari. probably a chrome "performance enhancement". ;-P

**Comment by jejacks0n** [comment]
#15 @MichaelArestad you should add `#15` to the title of your pull request so it gets attached to the issue.

**Comment by mikepack** [comment]
So close! Internet Explorer...thanks for ruining the show again. Below applies to IE10 and 11. Mostly checks out except the close button.

#### Close button not visible

screen shot 2014-09-02 at 10 27 48 pm

### Close button positioned off to the left

screen shot 2014-09-02 at 10 29 57 pm

**Comment by mikepack** [comment]
Whoops, hit shift+enter prematurely on the last comment, check on GitHub.

**Comment by mikepack** [comment]
I've uploaded the latest to S3 to make IE debugging easier: https://s3.amazonaws.com/nerdbox/demo.html

**Comment by MichaelArestad** [comment]
Dangit IE! Looked into it a little last night with no luck. Will try again on the airplane later today.

**Comment by jejacks0n** [comment]
This is very very close. After talking with @mikepack I think this gif accurately describes the elusive nature of the problem. Also, very impressed.

tumblr_lvwywaykn61qdku5lo1_500

**Comment by MichaelArestad** [comment]
Still no luck.
image

**Comment by mikepack** [comment]
tumblr_lcd16mm4dv1qdpjw9

This thing is so damn close. I'll keep testing and see if maybe we can make the X more visible on IE (looks like it's rendering behind the overlay?).

**Comment by MichaelArestad** [comment]
Yeah. It's either behind or to the left of the overlay. Without fixed positioning, I can get it to be on the top right, but then it scrolls with the item. As you've run into, when both the close and the content are absolute positioned, the container collapses. I also tried float hacks, but had the same issue where it won't remain fixed. I suspect the answer lies in a float/fixed hacky combo.

**Comment by mikepack** [comment]
I don't entirely follow, but that's why I have @ajaswa :) After a little more testing, I'd be happy calling this complete if the X rendered above the overlay (z-index style). Do you think that's a longshot?

**Comment by mikepack** [comment]
Dude, I owe you multiple beers sometime, but I merged in #18. Using viewport units, who would have guessed. :heart: :heart: :heart:

**Pull request closed without merging**
