### PR TITLE
Fix overflow issue without shim

### PR DESCRIPTION
**Pull request by jackrugile**
I think this meets the requirements for fixing #15. Please test and let me know.

### CODE REVIEW

**Comment by mikepack** [comment]
Nice stab, but the close button doesn't keep its top right position when scrolling around. Check out the close button in this screenshot.

screen shot 2014-09-02 at 9 02 23 pm

**Comment by jejacks0n** [comment]
I think that's an easy fix.

---

Jeremy Jackson

**Comment by mikepack** [comment]
Said @ajaswa :)

**Comment by jackrugile** [comment]
Yikes! Will take a look at that.

**Comment by jejacks0n** [comment]
@mikepack haha.. but for a professional I mean.

oh snap, sorry @ajaswa ;-P

**Comment by ajaswa** [comment]
@jejacks0n if you think you can fix it… by all means ;) I ran in to the same issue when I was trying to solve it. 

@jackrugile hit me up if you want to bounce some ideas around.

**Comment by jejacks0n** [comment]
#15

**Comment by mikepack** [comment]
Dude, I owe you multiple beers sometime, but I merged in #18. Using viewport units, who would have guessed. :heart: :heart: :heart:

**Comment by jackrugile** [comment]
Nice, that solution works great! Glad it got figured out ;)

**Pull request closed without merging**
